### ISSUE TITLE
Add recesses for the 3 rocket Leds

### ISSUE THREAD

**Issue by christian-draeger** [royrobotiks/card10_cover#1]
Could someone who is familiar with adjusting the model please add recesses for the three rocket leds that are shining through the harmonic board?
So the case would not cover any of the sensors and leds from card10. Maybe also with adjustable led diffusion thickness like for the row of leds on top.
Would try to print it with "transparent" pla and put a small plate of thin glass in the display cutout (fixed with glue)

**Comment by royrobotiks** [comment]
Hi Christian,
you can adjust the led diffusion layer thickness for the 11 led's on top already. Just change the value in line 28 of the OpenSCAD code: ledDiffusionThickness=.28;
Did I miss any cutouts for sensors? I understood that there's only the IR photo sensor below the 11 leds and the ecg+blood oximeter, which are both not covered. But yes, I covered the rocket led's and there could be cutouts, too. Those could be included e.g. as "cubes" between the lines 78 & 80.

**Comment by christian-draeger** [comment]
Thx for the fast response.
Yeah i mean the 3 rocket leds. Imho a solution simular to the led row on top (variant thickness) would be very nice. Since i have absolutely no clue regarding creating or adjusting 3d models it would be awesome if someone more experienced could adjust the model.
If it would have the same shape as the rockets would be perfect i think

**Comment by royrobotiks** [comment]
Hi Christian, I refined the scad file. Now it's generative and you can print a model with the features that you requested :)
